# Generated by Django 3.2.4 on 2021-06-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymSo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Cursos',
        ),
    ]
