# Generated by Django 3.2.4 on 2021-06-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymSo', '0002_rename_destination_cursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
