# Generated by Django 3.2.4 on 2021-06-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymSo', '0003_rename_cursos_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('delegacion', models.TextField()),
                ('twitter', models.TextField()),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymSo.curso')),
            ],
        ),
    ]
