# Generated by Django 3.2.4 on 2021-06-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymSo', '0004_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='img',
            field=models.ImageField(default=0, upload_to='perfilTrainer'),
            preserve_default=False,
        ),
    ]
