# Generated by Django 3.2.4 on 2021-06-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymSo', '0005_responsable_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='trainer',
        ),
        migrations.AddField(
            model_name='curso',
            name='days',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
